app = "tiusharpbot"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]

  [build.args]
    BP_DOTNET_PROJECT_PATH="./src/TiuSharpBot"

[[services]]
