app = "tiusharpbot"
primary_region = "hkg"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"
  buildpacks = ["paketo-buildpacks/dotnet-core"]

  [build.args]
    BP_DOTNET_PROJECT_PATH="./src/TiuSharpBot"

[env]
  BOT_PREFIX = "tiu!"

[[services]]
